---
- name: Install Grafana
  hosts: localhost
  become_user: root
  become: true
  gather_facts: false
  vars_files: 
    - vars.yml

  tasks: 
    - name: Update apt cache and repository
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - software-properties-common
          - wget
          - adduser
          - libfontconfig1
          - musl
        state: present
        update_cache: yes

    - name: Create the /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and add Grafana GPG key
      shell:
        cmd: "wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg"
      args:
        creates: /etc/apt/keyrings/grafana.gpg

    - name: Add Grafana APT repository
      blockinfile:
        path: /etc/apt/sources.list.d/grafana.list
        block: |
          deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
          deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com beta main
        create: yes

    - name: Update apt cache and repository
      apt:
        update_cache: yes

    # - name: Install Grafana
    #   apt:
    #     name: grafana
    #     state: present

    - name: Download Grafana DEB package
      get_url:
        url: https://dl.grafana.com/oss/release/grafana_10.4.2_amd64.deb
        dest: /opt/grafana_10.4.2_amd64.deb

    - name: Install Grafana from DEB package
      apt:
        deb: /opt/grafana_10.4.2_amd64.deb
        state: present

    - name: Stop Grafana service
      service:
        name: grafana-server
        state: stopped

    - name: Enable Grafana service
      service:
        name: grafana-server
        enabled: yes

    - name: Start Grafana service
      service:
        name: grafana-server
        state: started

    
